from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.applications.resnet import preprocess_input
from tensorflow.keras.applications.resnet import ResNet152
from tensorflow.keras.models import Model, load_model


def evaluate_waste(image, feature_model, model):
    # The image should be loaded with resolution (299 299) using the load_img function from tensorflow.keras.preprocessing.image
    # Example: image = load_img(image_path, target_size=(224, 224))

    # Preprocess the image
    image = img_to_array(image)  # Convert the image pixels to a numpy array
    image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))  # reshape data for the model
    image = preprocess_input(image)  # prepare the image for the ResNet50 model


    image_features = feature_model.predict(image)  # Get image features for the image

    # Return a prediction
    return model.predict(image_features)



def calculate_score(network_output):
    """
    Returns an integer score from 0 to 100 depending on the output from the network
    network_output should be a list of 4 float numbers (as generated by the neural network)
    """
    return min(100, int(network_output[1] * 33.33 + network_output[2] * 66.66 + network_output[3] * 100))
